### ISSUE TITLE
Bild wird nicht angezeigt - Bildergeschichten

### ISSUE THREAD

**Issue by tinsehau** [tinsehau/tinsehau.github.io#7]
- [ ] PRÄSE_FINAL-23.png

**Comment by rielc** [comment]
Ich habs mir nicht angeschaut, aber es könnte am Umlaut liegen. Am besten du ersetzt Umlaute, Sonderzeichen und Leerzeichen und beschränkst dich auf folgende Zeichen: `a-z 0-9 _ - + ,`

`PRÄSE_FINAL-23.png` --> `praese_final_23.png`
